---
- name: web-server configuration
  hosts: prod
  become: yes

  roles:
    - common
    - tomcat

- name: artefactory assembly configuration
  hosts: build
  become: yes

  roles:
    - artefact_builder